baseURL: https://xnacly.me
languageCode: en-us
title: "xnacly - blog"
theme: xnacly
canonifyURLs: true
paginate: 6

markup:
    highlight:
        style: dracula
        lineNos: true
        lineNumbersInTable: false
    tableOfContents:
        endLevel: 6
        ordered: false
        startLevel: 2

params:
    author: xnacly
    bio: Fullstack Developer and Tech enthusiast
    description: A blog all around tech, programming and whatever im currently interested in
    showPowerBy: false
    copyright: " "
    showToc: true
    enableRSS: true
    hiddenPostSummaryInHomePage: true
