languageCode: en-us
title: "xnacly - blog"
theme: xnacly
email: teo@xnacly.me
canonifyURLs: true
pagination:
  pagerSize: 4
enableRobotsTXT: false

markup:
  highlight:
    style: gruvbox
    lineNos: true
    lineNumbersInTable: false
  tableOfContents:
    endLevel: 6
    ordered: false
    startLevel: 2

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

params:
  author:
    name: xnacly
    email: contact@xnacly.me
  social:
    github: https://github.com/xnacly
    rss: https://xnacly.me/index.xml
    email: mailto:contact@xnacly.me
  bio: Fullstack Developer and Tech enthusiast
  description: A blog all around tech, programming and whatever im currently interested in
  showPowerBy: false
  showToc: true
  enableRSS: true
  hiddenPostSummaryInHomePage: false
